[package]
authors.workspace = true
version.workspace = true
edition.workspace = true
name = "js2py_translator"

[dependencies]
js2py_parser = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"